/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:cf2ae420-78ae-4d4a-b352-50b24d6ed97d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Ki4BUYoSf",
    "aws_user_pools_web_client_id": "58bt8fejnkrtiol5627dio7l0u",
    "oauth": {}
};

export default awsmobile;
